const fs = require('fs');
let lines = fs.readFileSync('Admin/employees_backup.html', 'utf8').split(/\r?\n/);
let out = lines.slice(0, 725);
out.push("            get(ref(db, 'companies')).then(snap => {");
out.push("                const companySelect = document.getElementById('companySelect');");
out.push("                if (companySelect) {");
out.push("                    companySelect.innerHTML += '<option value=\"teamsive\">Teamsive HQ (Internal)</option>';");
out.push("                    if (snap.exists()) {");
out.push("                        snap.forEach(child => {");
out.push("                            const c = child.val();");
out.push("                            const cId = child.key;");
out.push("                            if (cId !== 'teamsive') {");
out.push("                                const cName = c.companyName || cId;");
out.push("                                companySelect.innerHTML += `<option value=\"${cId}\">${cName} (${cId})</option>`;");
out.push("                            }");
out.push("                        });");
out.push("                    }");
out.push("                }");
out.push("            });");
out.push("        } else {");
Array.prototype.push.apply(out, lines.slice(919));
fs.writeFileSync('Admin/employees.html', out.join('\r\n'));
